# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Math Magic Aerodynamics
author: Roie R. Black
logo: lpp.gif

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: mmbook.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# add sphinx extensions
sphinx:
  extra_extensions:
    - sphinxcontrib.tikz


# Information about where the book exists on the web
repository:
  url: https://github.com/rblack42/math-magik-aerodynamics  # Online location of your book
  path_to_book: mmbook  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
